name: kilt
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Kilt blockchain nodes # 79 char long summary
description: |
  kilt nodes for the polkadot ecnsystem

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  mashnet-node:
    command: target/release/mashnet-node --dev --ws-port 9944 --ws-external
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs: [network-bind]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

  kilt-parachain:
    command: wrappers/kilt-parachain.sh 
    daemon: simple
    install-mode: disable
    refresh-mode: endure
    restart-condition: never
    plugs: [network-bind]
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8

parts:
  common-kilt:
    plugin: dump
    build-packages: [build-essential, libclang-dev]
    source: https://github.com/KILTprotocol/mashnet-node.git
    source-branch: develop
    override-build: |
      curl https://sh.rustup.rs -sSf | sh -s -- -y
      source $HOME/.cargo/env
       
      cargo build --release -p mashnet-node
      cargo build --release -p kilt-parachain
      mkdir -p $SNAPCRAFT_PART_INSTALL/target
      cp -a target/release $SNAPCRAFT_PART_INSTALL/target/
      cp -a dev-specs $SNAPCRAFT_PART_INSTALL/
    stage:
      - target/release/mashnet-node*
      - target/release/kilt-parachain*
      - dev-specs/*
    prime:
      - target/release/mashnet-node*
      - target/release/kilt-parachain*
      - wrappers/*
      - dev-specs/*

  wrappers:
    plugin: dump
    source-type: local
    source: .
    stage:
      - wrappers/

